### ISSUE TITLE
[EPIC]: Update endpoints function to use options

### ISSUE THREAD

**Issue by JulianToledano** [JulianToledano/goingecko#26]
Most of the API endpoints consist of one or more required query params and some optional ones. Currently the function signatures makes you pass all params (required and optional).

For example [`coins/market`](https://docs.coingecko.com/reference/coins-markets) where the only required param is `vs_currency`:
https://github.com/JulianToledano/goingecko/blob/2c1d3faaaa09f5f6b2ec2bf447312116c148465f/coins.go#L29

Update function signatures to accept all necessary ones and the optional as options.

## Option

Options could be defined as an interface with a func to apply {key,value} to url params.

```go
// Option is a generic option type
type Option interface {
	apply(*url.Values)
}
```

Then for each API endpoint a new interface must be defined to make sure to not pass invalid options to that endpoint.
```go
// CoinsMarketOption is specific to the CoinsMarket function
type CoinsMarketOption interface {
	Option
	isCoinsMarketOption()
}

// ids option definition
type idsOption struct{ ids []string }

// implement Option
func (o idsOption) apply(v *url.Values) { v.Set("ids", strings.Join(o.ids, ",")) }

// implement CoinsMarketOption
func (idsOption) isCoinsMarketOption() {}

// option function which return a CoinsMarketOption
func WithIDs(ids []string) CoinsMarketOption         { return idsOption{ids} }

// new CoinsMarket signature
func (c *Client) CoinsMarket(vsCurrency string, options ...CoinsMarketOption) ([]*coins.Market, error) {
```

## Endpoints to implement
- [ ] [Ping](https://docs.coingecko.com/reference/ping-server)
- [ ] [Key](https://docs.coingecko.com/reference/api-usage)
- [ ] [Simple](https://docs.coingecko.com/reference/simple-price)
- [x] [Coins](https://docs.coingecko.com/reference/coins-list)
- [ ] [Contract](https://docs.coingecko.com/reference/coins-contract-address)
- [ ] [Asset Platforms](https://docs.coingecko.com/reference/asset-platforms-list)
- [ ] [Categories](https://docs.coingecko.com/reference/coins-categories-list)
- [ ] [Exchanges](https://docs.coingecko.com/reference/exchanges)
- [ ] [Derivatives](https://docs.coingecko.com/reference/derivatives-tickers)
- [ ] [NFTs (Beta)](https://docs.coingecko.com/reference/nfts-list)
- [ ] [Exchange Rates](https://docs.coingecko.com/reference/exchange-rates)
- [ ] [Search](https://docs.coingecko.com/reference/search-data)
- [ ] [Trending](https://docs.coingecko.com/reference/trending-search)
- [ ] [Global](https://docs.coingecko.com/reference/crypto-global)
- [ ] [Companies (Beta)](https://docs.coingecko.com/reference/companies-public-treasury)
